// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.22.3
// source: dbmng.proto

package andproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DbmngClient is the client API for Dbmng service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DbmngClient interface {
	CreateServer(ctx context.Context, in *CreateServerRequest, opts ...grpc.CallOption) (*CreateServerResponse, error)
	UpdateServer(ctx context.Context, in *UpdateServerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteServer(ctx context.Context, in *DeleteServerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ReadServers(ctx context.Context, in *ReadServersRequest, opts ...grpc.CallOption) (*ReadServersResponse, error)
	CreateServerPool(ctx context.Context, in *CreateServerPoolRequest, opts ...grpc.CallOption) (*CreateServerPoolResponse, error)
	UpdateServerPool(ctx context.Context, in *UpdateServerPoolRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteServerPool(ctx context.Context, in *DeleteServerPoolRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ReadServerPools(ctx context.Context, in *ReadServerPoolsRequest, opts ...grpc.CallOption) (*ReadServerPoolsResponse, error)
	CreateProxyFilter(ctx context.Context, in *CreateProxyFilterRequest, opts ...grpc.CallOption) (*CreateProxyFilterResponse, error)
	UpdateProxyFilter(ctx context.Context, in *UpdateProxyFilterRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteProxyFilter(ctx context.Context, in *DeleteProxyFilterRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ReadProxyFilters(ctx context.Context, in *ReadProxyFiltersRequest, opts ...grpc.CallOption) (*ReadProxyFiltersResponse, error)
	CreateL4Handler(ctx context.Context, in *CreateL4HandlerRequest, opts ...grpc.CallOption) (*CreateL4HandlerResponse, error)
	UpdateL4Handler(ctx context.Context, in *UpdateL4HandlerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteL4Handler(ctx context.Context, in *DeleteL4HandlerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ReadL4Handlers(ctx context.Context, in *ReadL4HandlersRequest, opts ...grpc.CallOption) (*ReadL4HandlersResponse, error)
	CreateAcl(ctx context.Context, in *CreateAclRequest, opts ...grpc.CallOption) (*CreateAclResponse, error)
	UpdateAcl(ctx context.Context, in *UpdateAclRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteAcl(ctx context.Context, in *DeleteAclRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ReadAcls(ctx context.Context, in *ReadAclsRequest, opts ...grpc.CallOption) (*ReadAclsResponse, error)
	CreateHttpPath(ctx context.Context, in *CreateHttpPathRequest, opts ...grpc.CallOption) (*CreateHttpPathResponse, error)
	UpdateHttpPath(ctx context.Context, in *UpdateHttpPathRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteHttpPath(ctx context.Context, in *DeleteHttpPathRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ReadHttpPaths(ctx context.Context, in *ReadHttpPathsRequest, opts ...grpc.CallOption) (*ReadHttpPathsResponse, error)
	CreateHttpHost(ctx context.Context, in *CreateHttpHostRequest, opts ...grpc.CallOption) (*CreateHttpHostResponse, error)
	UpdateHttpHost(ctx context.Context, in *UpdateHttpHostRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteHttpHost(ctx context.Context, in *DeleteHttpHostRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ReadHttpHosts(ctx context.Context, in *ReadHttpHostsRequest, opts ...grpc.CallOption) (*ReadHttpHostsResponse, error)
	CreateHttpHandler(ctx context.Context, in *CreateHttpHandlerRequest, opts ...grpc.CallOption) (*CreateHttpHandlerResponse, error)
	UpdateHttpHandler(ctx context.Context, in *UpdateHttpHandlerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteHttpHandler(ctx context.Context, in *DeleteHttpHandlerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ReadHttpHandlers(ctx context.Context, in *ReadHttpHandlersRequest, opts ...grpc.CallOption) (*ReadHttpHandlersResponse, error)
}

type dbmngClient struct {
	cc grpc.ClientConnInterface
}

func NewDbmngClient(cc grpc.ClientConnInterface) DbmngClient {
	return &dbmngClient{cc}
}

func (c *dbmngClient) CreateServer(ctx context.Context, in *CreateServerRequest, opts ...grpc.CallOption) (*CreateServerResponse, error) {
	out := new(CreateServerResponse)
	err := c.cc.Invoke(ctx, "/proto.Dbmng/CreateServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbmngClient) UpdateServer(ctx context.Context, in *UpdateServerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/proto.Dbmng/UpdateServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbmngClient) DeleteServer(ctx context.Context, in *DeleteServerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/proto.Dbmng/DeleteServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbmngClient) ReadServers(ctx context.Context, in *ReadServersRequest, opts ...grpc.CallOption) (*ReadServersResponse, error) {
	out := new(ReadServersResponse)
	err := c.cc.Invoke(ctx, "/proto.Dbmng/ReadServers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbmngClient) CreateServerPool(ctx context.Context, in *CreateServerPoolRequest, opts ...grpc.CallOption) (*CreateServerPoolResponse, error) {
	out := new(CreateServerPoolResponse)
	err := c.cc.Invoke(ctx, "/proto.Dbmng/CreateServerPool", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbmngClient) UpdateServerPool(ctx context.Context, in *UpdateServerPoolRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/proto.Dbmng/UpdateServerPool", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbmngClient) DeleteServerPool(ctx context.Context, in *DeleteServerPoolRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/proto.Dbmng/DeleteServerPool", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbmngClient) ReadServerPools(ctx context.Context, in *ReadServerPoolsRequest, opts ...grpc.CallOption) (*ReadServerPoolsResponse, error) {
	out := new(ReadServerPoolsResponse)
	err := c.cc.Invoke(ctx, "/proto.Dbmng/ReadServerPools", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbmngClient) CreateProxyFilter(ctx context.Context, in *CreateProxyFilterRequest, opts ...grpc.CallOption) (*CreateProxyFilterResponse, error) {
	out := new(CreateProxyFilterResponse)
	err := c.cc.Invoke(ctx, "/proto.Dbmng/CreateProxyFilter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbmngClient) UpdateProxyFilter(ctx context.Context, in *UpdateProxyFilterRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/proto.Dbmng/UpdateProxyFilter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbmngClient) DeleteProxyFilter(ctx context.Context, in *DeleteProxyFilterRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/proto.Dbmng/DeleteProxyFilter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbmngClient) ReadProxyFilters(ctx context.Context, in *ReadProxyFiltersRequest, opts ...grpc.CallOption) (*ReadProxyFiltersResponse, error) {
	out := new(ReadProxyFiltersResponse)
	err := c.cc.Invoke(ctx, "/proto.Dbmng/ReadProxyFilters", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbmngClient) CreateL4Handler(ctx context.Context, in *CreateL4HandlerRequest, opts ...grpc.CallOption) (*CreateL4HandlerResponse, error) {
	out := new(CreateL4HandlerResponse)
	err := c.cc.Invoke(ctx, "/proto.Dbmng/CreateL4Handler", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbmngClient) UpdateL4Handler(ctx context.Context, in *UpdateL4HandlerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/proto.Dbmng/UpdateL4Handler", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbmngClient) DeleteL4Handler(ctx context.Context, in *DeleteL4HandlerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/proto.Dbmng/DeleteL4Handler", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbmngClient) ReadL4Handlers(ctx context.Context, in *ReadL4HandlersRequest, opts ...grpc.CallOption) (*ReadL4HandlersResponse, error) {
	out := new(ReadL4HandlersResponse)
	err := c.cc.Invoke(ctx, "/proto.Dbmng/ReadL4Handlers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbmngClient) CreateAcl(ctx context.Context, in *CreateAclRequest, opts ...grpc.CallOption) (*CreateAclResponse, error) {
	out := new(CreateAclResponse)
	err := c.cc.Invoke(ctx, "/proto.Dbmng/CreateAcl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbmngClient) UpdateAcl(ctx context.Context, in *UpdateAclRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/proto.Dbmng/UpdateAcl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbmngClient) DeleteAcl(ctx context.Context, in *DeleteAclRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/proto.Dbmng/DeleteAcl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbmngClient) ReadAcls(ctx context.Context, in *ReadAclsRequest, opts ...grpc.CallOption) (*ReadAclsResponse, error) {
	out := new(ReadAclsResponse)
	err := c.cc.Invoke(ctx, "/proto.Dbmng/ReadAcls", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbmngClient) CreateHttpPath(ctx context.Context, in *CreateHttpPathRequest, opts ...grpc.CallOption) (*CreateHttpPathResponse, error) {
	out := new(CreateHttpPathResponse)
	err := c.cc.Invoke(ctx, "/proto.Dbmng/CreateHttpPath", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbmngClient) UpdateHttpPath(ctx context.Context, in *UpdateHttpPathRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/proto.Dbmng/UpdateHttpPath", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbmngClient) DeleteHttpPath(ctx context.Context, in *DeleteHttpPathRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/proto.Dbmng/DeleteHttpPath", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbmngClient) ReadHttpPaths(ctx context.Context, in *ReadHttpPathsRequest, opts ...grpc.CallOption) (*ReadHttpPathsResponse, error) {
	out := new(ReadHttpPathsResponse)
	err := c.cc.Invoke(ctx, "/proto.Dbmng/ReadHttpPaths", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbmngClient) CreateHttpHost(ctx context.Context, in *CreateHttpHostRequest, opts ...grpc.CallOption) (*CreateHttpHostResponse, error) {
	out := new(CreateHttpHostResponse)
	err := c.cc.Invoke(ctx, "/proto.Dbmng/CreateHttpHost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbmngClient) UpdateHttpHost(ctx context.Context, in *UpdateHttpHostRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/proto.Dbmng/UpdateHttpHost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbmngClient) DeleteHttpHost(ctx context.Context, in *DeleteHttpHostRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/proto.Dbmng/DeleteHttpHost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbmngClient) ReadHttpHosts(ctx context.Context, in *ReadHttpHostsRequest, opts ...grpc.CallOption) (*ReadHttpHostsResponse, error) {
	out := new(ReadHttpHostsResponse)
	err := c.cc.Invoke(ctx, "/proto.Dbmng/ReadHttpHosts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbmngClient) CreateHttpHandler(ctx context.Context, in *CreateHttpHandlerRequest, opts ...grpc.CallOption) (*CreateHttpHandlerResponse, error) {
	out := new(CreateHttpHandlerResponse)
	err := c.cc.Invoke(ctx, "/proto.Dbmng/CreateHttpHandler", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbmngClient) UpdateHttpHandler(ctx context.Context, in *UpdateHttpHandlerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/proto.Dbmng/UpdateHttpHandler", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbmngClient) DeleteHttpHandler(ctx context.Context, in *DeleteHttpHandlerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/proto.Dbmng/DeleteHttpHandler", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbmngClient) ReadHttpHandlers(ctx context.Context, in *ReadHttpHandlersRequest, opts ...grpc.CallOption) (*ReadHttpHandlersResponse, error) {
	out := new(ReadHttpHandlersResponse)
	err := c.cc.Invoke(ctx, "/proto.Dbmng/ReadHttpHandlers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DbmngServer is the server API for Dbmng service.
// All implementations must embed UnimplementedDbmngServer
// for forward compatibility
type DbmngServer interface {
	CreateServer(context.Context, *CreateServerRequest) (*CreateServerResponse, error)
	UpdateServer(context.Context, *UpdateServerRequest) (*emptypb.Empty, error)
	DeleteServer(context.Context, *DeleteServerRequest) (*emptypb.Empty, error)
	ReadServers(context.Context, *ReadServersRequest) (*ReadServersResponse, error)
	CreateServerPool(context.Context, *CreateServerPoolRequest) (*CreateServerPoolResponse, error)
	UpdateServerPool(context.Context, *UpdateServerPoolRequest) (*emptypb.Empty, error)
	DeleteServerPool(context.Context, *DeleteServerPoolRequest) (*emptypb.Empty, error)
	ReadServerPools(context.Context, *ReadServerPoolsRequest) (*ReadServerPoolsResponse, error)
	CreateProxyFilter(context.Context, *CreateProxyFilterRequest) (*CreateProxyFilterResponse, error)
	UpdateProxyFilter(context.Context, *UpdateProxyFilterRequest) (*emptypb.Empty, error)
	DeleteProxyFilter(context.Context, *DeleteProxyFilterRequest) (*emptypb.Empty, error)
	ReadProxyFilters(context.Context, *ReadProxyFiltersRequest) (*ReadProxyFiltersResponse, error)
	CreateL4Handler(context.Context, *CreateL4HandlerRequest) (*CreateL4HandlerResponse, error)
	UpdateL4Handler(context.Context, *UpdateL4HandlerRequest) (*emptypb.Empty, error)
	DeleteL4Handler(context.Context, *DeleteL4HandlerRequest) (*emptypb.Empty, error)
	ReadL4Handlers(context.Context, *ReadL4HandlersRequest) (*ReadL4HandlersResponse, error)
	CreateAcl(context.Context, *CreateAclRequest) (*CreateAclResponse, error)
	UpdateAcl(context.Context, *UpdateAclRequest) (*emptypb.Empty, error)
	DeleteAcl(context.Context, *DeleteAclRequest) (*emptypb.Empty, error)
	ReadAcls(context.Context, *ReadAclsRequest) (*ReadAclsResponse, error)
	CreateHttpPath(context.Context, *CreateHttpPathRequest) (*CreateHttpPathResponse, error)
	UpdateHttpPath(context.Context, *UpdateHttpPathRequest) (*emptypb.Empty, error)
	DeleteHttpPath(context.Context, *DeleteHttpPathRequest) (*emptypb.Empty, error)
	ReadHttpPaths(context.Context, *ReadHttpPathsRequest) (*ReadHttpPathsResponse, error)
	CreateHttpHost(context.Context, *CreateHttpHostRequest) (*CreateHttpHostResponse, error)
	UpdateHttpHost(context.Context, *UpdateHttpHostRequest) (*emptypb.Empty, error)
	DeleteHttpHost(context.Context, *DeleteHttpHostRequest) (*emptypb.Empty, error)
	ReadHttpHosts(context.Context, *ReadHttpHostsRequest) (*ReadHttpHostsResponse, error)
	CreateHttpHandler(context.Context, *CreateHttpHandlerRequest) (*CreateHttpHandlerResponse, error)
	UpdateHttpHandler(context.Context, *UpdateHttpHandlerRequest) (*emptypb.Empty, error)
	DeleteHttpHandler(context.Context, *DeleteHttpHandlerRequest) (*emptypb.Empty, error)
	ReadHttpHandlers(context.Context, *ReadHttpHandlersRequest) (*ReadHttpHandlersResponse, error)
	mustEmbedUnimplementedDbmngServer()
}

// UnimplementedDbmngServer must be embedded to have forward compatible implementations.
type UnimplementedDbmngServer struct {
}

func (UnimplementedDbmngServer) CreateServer(context.Context, *CreateServerRequest) (*CreateServerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateServer not implemented")
}
func (UnimplementedDbmngServer) UpdateServer(context.Context, *UpdateServerRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateServer not implemented")
}
func (UnimplementedDbmngServer) DeleteServer(context.Context, *DeleteServerRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteServer not implemented")
}
func (UnimplementedDbmngServer) ReadServers(context.Context, *ReadServersRequest) (*ReadServersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadServers not implemented")
}
func (UnimplementedDbmngServer) CreateServerPool(context.Context, *CreateServerPoolRequest) (*CreateServerPoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateServerPool not implemented")
}
func (UnimplementedDbmngServer) UpdateServerPool(context.Context, *UpdateServerPoolRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateServerPool not implemented")
}
func (UnimplementedDbmngServer) DeleteServerPool(context.Context, *DeleteServerPoolRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteServerPool not implemented")
}
func (UnimplementedDbmngServer) ReadServerPools(context.Context, *ReadServerPoolsRequest) (*ReadServerPoolsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadServerPools not implemented")
}
func (UnimplementedDbmngServer) CreateProxyFilter(context.Context, *CreateProxyFilterRequest) (*CreateProxyFilterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProxyFilter not implemented")
}
func (UnimplementedDbmngServer) UpdateProxyFilter(context.Context, *UpdateProxyFilterRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProxyFilter not implemented")
}
func (UnimplementedDbmngServer) DeleteProxyFilter(context.Context, *DeleteProxyFilterRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProxyFilter not implemented")
}
func (UnimplementedDbmngServer) ReadProxyFilters(context.Context, *ReadProxyFiltersRequest) (*ReadProxyFiltersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadProxyFilters not implemented")
}
func (UnimplementedDbmngServer) CreateL4Handler(context.Context, *CreateL4HandlerRequest) (*CreateL4HandlerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateL4Handler not implemented")
}
func (UnimplementedDbmngServer) UpdateL4Handler(context.Context, *UpdateL4HandlerRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateL4Handler not implemented")
}
func (UnimplementedDbmngServer) DeleteL4Handler(context.Context, *DeleteL4HandlerRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteL4Handler not implemented")
}
func (UnimplementedDbmngServer) ReadL4Handlers(context.Context, *ReadL4HandlersRequest) (*ReadL4HandlersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadL4Handlers not implemented")
}
func (UnimplementedDbmngServer) CreateAcl(context.Context, *CreateAclRequest) (*CreateAclResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAcl not implemented")
}
func (UnimplementedDbmngServer) UpdateAcl(context.Context, *UpdateAclRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAcl not implemented")
}
func (UnimplementedDbmngServer) DeleteAcl(context.Context, *DeleteAclRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAcl not implemented")
}
func (UnimplementedDbmngServer) ReadAcls(context.Context, *ReadAclsRequest) (*ReadAclsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadAcls not implemented")
}
func (UnimplementedDbmngServer) CreateHttpPath(context.Context, *CreateHttpPathRequest) (*CreateHttpPathResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateHttpPath not implemented")
}
func (UnimplementedDbmngServer) UpdateHttpPath(context.Context, *UpdateHttpPathRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateHttpPath not implemented")
}
func (UnimplementedDbmngServer) DeleteHttpPath(context.Context, *DeleteHttpPathRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteHttpPath not implemented")
}
func (UnimplementedDbmngServer) ReadHttpPaths(context.Context, *ReadHttpPathsRequest) (*ReadHttpPathsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadHttpPaths not implemented")
}
func (UnimplementedDbmngServer) CreateHttpHost(context.Context, *CreateHttpHostRequest) (*CreateHttpHostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateHttpHost not implemented")
}
func (UnimplementedDbmngServer) UpdateHttpHost(context.Context, *UpdateHttpHostRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateHttpHost not implemented")
}
func (UnimplementedDbmngServer) DeleteHttpHost(context.Context, *DeleteHttpHostRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteHttpHost not implemented")
}
func (UnimplementedDbmngServer) ReadHttpHosts(context.Context, *ReadHttpHostsRequest) (*ReadHttpHostsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadHttpHosts not implemented")
}
func (UnimplementedDbmngServer) CreateHttpHandler(context.Context, *CreateHttpHandlerRequest) (*CreateHttpHandlerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateHttpHandler not implemented")
}
func (UnimplementedDbmngServer) UpdateHttpHandler(context.Context, *UpdateHttpHandlerRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateHttpHandler not implemented")
}
func (UnimplementedDbmngServer) DeleteHttpHandler(context.Context, *DeleteHttpHandlerRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteHttpHandler not implemented")
}
func (UnimplementedDbmngServer) ReadHttpHandlers(context.Context, *ReadHttpHandlersRequest) (*ReadHttpHandlersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadHttpHandlers not implemented")
}
func (UnimplementedDbmngServer) mustEmbedUnimplementedDbmngServer() {}

// UnsafeDbmngServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DbmngServer will
// result in compilation errors.
type UnsafeDbmngServer interface {
	mustEmbedUnimplementedDbmngServer()
}

func RegisterDbmngServer(s grpc.ServiceRegistrar, srv DbmngServer) {
	s.RegisterService(&Dbmng_ServiceDesc, srv)
}

func _Dbmng_CreateServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbmngServer).CreateServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Dbmng/CreateServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbmngServer).CreateServer(ctx, req.(*CreateServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dbmng_UpdateServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbmngServer).UpdateServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Dbmng/UpdateServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbmngServer).UpdateServer(ctx, req.(*UpdateServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dbmng_DeleteServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbmngServer).DeleteServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Dbmng/DeleteServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbmngServer).DeleteServer(ctx, req.(*DeleteServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dbmng_ReadServers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadServersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbmngServer).ReadServers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Dbmng/ReadServers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbmngServer).ReadServers(ctx, req.(*ReadServersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dbmng_CreateServerPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateServerPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbmngServer).CreateServerPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Dbmng/CreateServerPool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbmngServer).CreateServerPool(ctx, req.(*CreateServerPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dbmng_UpdateServerPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateServerPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbmngServer).UpdateServerPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Dbmng/UpdateServerPool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbmngServer).UpdateServerPool(ctx, req.(*UpdateServerPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dbmng_DeleteServerPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteServerPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbmngServer).DeleteServerPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Dbmng/DeleteServerPool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbmngServer).DeleteServerPool(ctx, req.(*DeleteServerPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dbmng_ReadServerPools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadServerPoolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbmngServer).ReadServerPools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Dbmng/ReadServerPools",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbmngServer).ReadServerPools(ctx, req.(*ReadServerPoolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dbmng_CreateProxyFilter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProxyFilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbmngServer).CreateProxyFilter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Dbmng/CreateProxyFilter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbmngServer).CreateProxyFilter(ctx, req.(*CreateProxyFilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dbmng_UpdateProxyFilter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProxyFilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbmngServer).UpdateProxyFilter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Dbmng/UpdateProxyFilter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbmngServer).UpdateProxyFilter(ctx, req.(*UpdateProxyFilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dbmng_DeleteProxyFilter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProxyFilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbmngServer).DeleteProxyFilter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Dbmng/DeleteProxyFilter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbmngServer).DeleteProxyFilter(ctx, req.(*DeleteProxyFilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dbmng_ReadProxyFilters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadProxyFiltersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbmngServer).ReadProxyFilters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Dbmng/ReadProxyFilters",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbmngServer).ReadProxyFilters(ctx, req.(*ReadProxyFiltersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dbmng_CreateL4Handler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateL4HandlerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbmngServer).CreateL4Handler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Dbmng/CreateL4Handler",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbmngServer).CreateL4Handler(ctx, req.(*CreateL4HandlerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dbmng_UpdateL4Handler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateL4HandlerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbmngServer).UpdateL4Handler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Dbmng/UpdateL4Handler",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbmngServer).UpdateL4Handler(ctx, req.(*UpdateL4HandlerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dbmng_DeleteL4Handler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteL4HandlerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbmngServer).DeleteL4Handler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Dbmng/DeleteL4Handler",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbmngServer).DeleteL4Handler(ctx, req.(*DeleteL4HandlerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dbmng_ReadL4Handlers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadL4HandlersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbmngServer).ReadL4Handlers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Dbmng/ReadL4Handlers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbmngServer).ReadL4Handlers(ctx, req.(*ReadL4HandlersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dbmng_CreateAcl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAclRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbmngServer).CreateAcl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Dbmng/CreateAcl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbmngServer).CreateAcl(ctx, req.(*CreateAclRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dbmng_UpdateAcl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAclRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbmngServer).UpdateAcl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Dbmng/UpdateAcl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbmngServer).UpdateAcl(ctx, req.(*UpdateAclRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dbmng_DeleteAcl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAclRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbmngServer).DeleteAcl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Dbmng/DeleteAcl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbmngServer).DeleteAcl(ctx, req.(*DeleteAclRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dbmng_ReadAcls_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAclsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbmngServer).ReadAcls(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Dbmng/ReadAcls",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbmngServer).ReadAcls(ctx, req.(*ReadAclsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dbmng_CreateHttpPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateHttpPathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbmngServer).CreateHttpPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Dbmng/CreateHttpPath",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbmngServer).CreateHttpPath(ctx, req.(*CreateHttpPathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dbmng_UpdateHttpPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateHttpPathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbmngServer).UpdateHttpPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Dbmng/UpdateHttpPath",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbmngServer).UpdateHttpPath(ctx, req.(*UpdateHttpPathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dbmng_DeleteHttpPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteHttpPathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbmngServer).DeleteHttpPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Dbmng/DeleteHttpPath",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbmngServer).DeleteHttpPath(ctx, req.(*DeleteHttpPathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dbmng_ReadHttpPaths_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadHttpPathsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbmngServer).ReadHttpPaths(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Dbmng/ReadHttpPaths",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbmngServer).ReadHttpPaths(ctx, req.(*ReadHttpPathsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dbmng_CreateHttpHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateHttpHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbmngServer).CreateHttpHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Dbmng/CreateHttpHost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbmngServer).CreateHttpHost(ctx, req.(*CreateHttpHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dbmng_UpdateHttpHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateHttpHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbmngServer).UpdateHttpHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Dbmng/UpdateHttpHost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbmngServer).UpdateHttpHost(ctx, req.(*UpdateHttpHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dbmng_DeleteHttpHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteHttpHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbmngServer).DeleteHttpHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Dbmng/DeleteHttpHost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbmngServer).DeleteHttpHost(ctx, req.(*DeleteHttpHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dbmng_ReadHttpHosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadHttpHostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbmngServer).ReadHttpHosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Dbmng/ReadHttpHosts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbmngServer).ReadHttpHosts(ctx, req.(*ReadHttpHostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dbmng_CreateHttpHandler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateHttpHandlerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbmngServer).CreateHttpHandler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Dbmng/CreateHttpHandler",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbmngServer).CreateHttpHandler(ctx, req.(*CreateHttpHandlerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dbmng_UpdateHttpHandler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateHttpHandlerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbmngServer).UpdateHttpHandler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Dbmng/UpdateHttpHandler",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbmngServer).UpdateHttpHandler(ctx, req.(*UpdateHttpHandlerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dbmng_DeleteHttpHandler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteHttpHandlerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbmngServer).DeleteHttpHandler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Dbmng/DeleteHttpHandler",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbmngServer).DeleteHttpHandler(ctx, req.(*DeleteHttpHandlerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dbmng_ReadHttpHandlers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadHttpHandlersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbmngServer).ReadHttpHandlers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Dbmng/ReadHttpHandlers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbmngServer).ReadHttpHandlers(ctx, req.(*ReadHttpHandlersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Dbmng_ServiceDesc is the grpc.ServiceDesc for Dbmng service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Dbmng_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Dbmng",
	HandlerType: (*DbmngServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateServer",
			Handler:    _Dbmng_CreateServer_Handler,
		},
		{
			MethodName: "UpdateServer",
			Handler:    _Dbmng_UpdateServer_Handler,
		},
		{
			MethodName: "DeleteServer",
			Handler:    _Dbmng_DeleteServer_Handler,
		},
		{
			MethodName: "ReadServers",
			Handler:    _Dbmng_ReadServers_Handler,
		},
		{
			MethodName: "CreateServerPool",
			Handler:    _Dbmng_CreateServerPool_Handler,
		},
		{
			MethodName: "UpdateServerPool",
			Handler:    _Dbmng_UpdateServerPool_Handler,
		},
		{
			MethodName: "DeleteServerPool",
			Handler:    _Dbmng_DeleteServerPool_Handler,
		},
		{
			MethodName: "ReadServerPools",
			Handler:    _Dbmng_ReadServerPools_Handler,
		},
		{
			MethodName: "CreateProxyFilter",
			Handler:    _Dbmng_CreateProxyFilter_Handler,
		},
		{
			MethodName: "UpdateProxyFilter",
			Handler:    _Dbmng_UpdateProxyFilter_Handler,
		},
		{
			MethodName: "DeleteProxyFilter",
			Handler:    _Dbmng_DeleteProxyFilter_Handler,
		},
		{
			MethodName: "ReadProxyFilters",
			Handler:    _Dbmng_ReadProxyFilters_Handler,
		},
		{
			MethodName: "CreateL4Handler",
			Handler:    _Dbmng_CreateL4Handler_Handler,
		},
		{
			MethodName: "UpdateL4Handler",
			Handler:    _Dbmng_UpdateL4Handler_Handler,
		},
		{
			MethodName: "DeleteL4Handler",
			Handler:    _Dbmng_DeleteL4Handler_Handler,
		},
		{
			MethodName: "ReadL4Handlers",
			Handler:    _Dbmng_ReadL4Handlers_Handler,
		},
		{
			MethodName: "CreateAcl",
			Handler:    _Dbmng_CreateAcl_Handler,
		},
		{
			MethodName: "UpdateAcl",
			Handler:    _Dbmng_UpdateAcl_Handler,
		},
		{
			MethodName: "DeleteAcl",
			Handler:    _Dbmng_DeleteAcl_Handler,
		},
		{
			MethodName: "ReadAcls",
			Handler:    _Dbmng_ReadAcls_Handler,
		},
		{
			MethodName: "CreateHttpPath",
			Handler:    _Dbmng_CreateHttpPath_Handler,
		},
		{
			MethodName: "UpdateHttpPath",
			Handler:    _Dbmng_UpdateHttpPath_Handler,
		},
		{
			MethodName: "DeleteHttpPath",
			Handler:    _Dbmng_DeleteHttpPath_Handler,
		},
		{
			MethodName: "ReadHttpPaths",
			Handler:    _Dbmng_ReadHttpPaths_Handler,
		},
		{
			MethodName: "CreateHttpHost",
			Handler:    _Dbmng_CreateHttpHost_Handler,
		},
		{
			MethodName: "UpdateHttpHost",
			Handler:    _Dbmng_UpdateHttpHost_Handler,
		},
		{
			MethodName: "DeleteHttpHost",
			Handler:    _Dbmng_DeleteHttpHost_Handler,
		},
		{
			MethodName: "ReadHttpHosts",
			Handler:    _Dbmng_ReadHttpHosts_Handler,
		},
		{
			MethodName: "CreateHttpHandler",
			Handler:    _Dbmng_CreateHttpHandler_Handler,
		},
		{
			MethodName: "UpdateHttpHandler",
			Handler:    _Dbmng_UpdateHttpHandler_Handler,
		},
		{
			MethodName: "DeleteHttpHandler",
			Handler:    _Dbmng_DeleteHttpHandler_Handler,
		},
		{
			MethodName: "ReadHttpHandlers",
			Handler:    _Dbmng_ReadHttpHandlers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dbmng.proto",
}
